name: Build

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - run: npm run verify
      - name: Coveralls
        uses: coverallsapp/github-action@master
        env:
          NODE_COVERALLS_DEBUG: 1
        with:
          path-to-lcov: client/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        env:
          NODE_COVERALLS_DEBUG: 1
        with:
          path-to-lcov: coverage/lcov.info
          github-token: ${{ secrets.github_token }}
